### ISSUE TITLE
[Documentation] Tunnel config file

### ISSUE THREAD

**Issue by hackmonker** [Erisa/cloudflared-docker#3]
Anyway we can add a configuration file for cloudflared to look at? Did not see  it mention anywhere so asked

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file

**Comment by hackmonker** [comment]
Ah we can add in command if I am not wrong

**Comment by Erisa** [comment]
You can mount a config file to `/etc/cloudflared/config.yml` in the container.

e.g. `docker run -v $PWD/config.yml:/etc/cloudflared/config.yml erisamoe/cloudflared`

**Comment by hackmonker** [comment]
I am using compose
 so we run that command once?

**Comment by Erisa** [comment]
No, you include it as a volume in your compose file:
```yml
  cloudflared:
    image: erisamoe/cloudflared
    volumes:
        - ./config.yml:/etc/cloudflared/config.yml
```

You may also want to mount other files like your `cert.pem` or your tunnels json credentials file. Add these as extra volumes in the compose file.

Eventually I hope to add this to the docs here: https://docs.erisa.uk/cloudflared-docker/
But right now haven't found the time.
