### ISSUE TITLE
"you are using Cloudflare Tunnel in a (legacy) way that is no longer supported.Migrate to Named Tunnels to continue exposing your private origin through Cloudflare's Network" error message

### ISSUE THREAD

**Issue by mendhak** [Erisa/cloudflared-docker#5]
Is anyone else getting this error after days of no problems with the tunnel?

calibre-web-cloudflared | 2022-04-23T14:15:54Z ERR Connection terminated error="you are using Cloudflare Tunnel in a (legacy) way that is no longer supported.Migrate to Named Tunnels to continue exposing your private origin through Cloudflare's Network.You can follow this guide: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/migrate-legacy-tunnels as an example.Alternatively, you can go to https://dash.teams.cloudflare.com/ -> Access -> Tunnels -> Create and rely on the User Interface instead." connIndex=3

My docker compose is very simple, and has been working until just today

```
  cloudflared:
    image: erisamoe/cloudflared
    container_name: calibre-web-cloudflared
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: --hostname xxxx.xxxxx.com --url http://nginx:80
    depends_on:
      - nginx
```
